server:
  port: 5055

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5051/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 5054
      password: ${REDIS_PASSWORD}

  cache:
    type: redis

  flyway:
    enabled: false
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          # !! IMPORTANTE: Lembre-se de substituir 'seu-realm' pelo nome do seu realm no Keycloak !!
          issuer-uri: http://localhost:5052/realms/${REALM_KEYCLOAK}
  jackson:
    time-zone: America/Sao_Paulo

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# http://localhost:5055/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html

application:
  upload:
    base-directory: uploads